### PR TITLE
update to 3.10.106

### PR DESCRIPTION
**Pull request by zeadope**

### CODE REVIEW

**Comment by T1mpp4** [comment]
Thanks!

How much trouble was this? Did you get through all the conflicts easily?

**Comment by zeadope** [comment]
@T1mpp4 It wasn't that hard. But you should try and compile it first to see if it was successful. :)

**Comment by T1mpp4** [comment]
There is one error when building (net/ipv4/ping.c):

`GEN     /home/timi/android/hwgra_kernel/out/Makefile
  CHK     include/generated/uapi/linux/version.h
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  Using /home/timi/android/hwgra_kernel/android_kernel_hwgra as source for kernel
  CHK     include/generated/utsrelease.h
  CALL    /home/timi/android/hwgra_kernel/android_kernel_hwgra/scripts/checksyscalls.sh
  HOSTLD  scripts/mod/modpost
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  CC      net/ipv4/ping.o
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:50:26: error: static declaration of 'ping_table' follows non-static declaration
 static struct ping_table ping_table;
                          ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:55:26: note: previous declaration of 'ping_table' was here
 extern struct ping_table ping_table;
                          ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:205:12: error: static declaration of 'ping_init_sock' follows non-static declaration
 static int ping_init_sock(struct sock *sk)
            ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:71:6: note: previous declaration of 'ping_init_sock' was here
 int  ping_init_sock(struct sock *sk);
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:238:13: error: static declaration of 'ping_close' follows non-static declaration
 static void ping_close(struct sock *sk, long timeout)
             ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:72:6: note: previous declaration of 'ping_close' was here
 void ping_close(struct sock *sk, long timeout);
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:252:12: error: static declaration of 'ping_bind' follows non-static declaration
 static int ping_bind(struct sock *sk, struct sockaddr *uaddr, int addr_len)
            ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:73:6: note: previous declaration of 'ping_bind' was here
 int  ping_bind(struct sock *sk, struct sockaddr *uaddr, int addr_len);
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:327:12: error: static declaration of 'ping_queue_rcv_skb' follows non-static declaration
 static int ping_queue_rcv_skb(struct sock *sk, struct sk_buff *skb);
            ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:86:6: note: previous declaration of 'ping_queue_rcv_skb' was here
 int  ping_queue_rcv_skb(struct sock *sk, struct sk_buff *skb);
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:329:6: error: conflicting types for 'ping_err'
 void ping_err(struct sk_buff *skb, u32 info)
      ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:74:6: note: previous declaration of 'ping_err' was here
 void ping_err(struct sk_buff *skb, int offset, u32 info);
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:419:8: error: redefinition of 'struct pingfakehdr'
 struct pingfakehdr {
        ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:60:8: note: originally defined here
 struct pingfakehdr {
        ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:425:12: error: static declaration of 'ping_getfrag' follows non-static declaration
 static int ping_getfrag(void *from, char *to,
            ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:75:6: note: previous declaration of 'ping_getfrag' was here
 int  ping_getfrag(void *from, char *to, int offset, int fraglen, int odd,
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c: In function 'ping_sendmsg':
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:576:7: error: too few arguments to function 'flowi4_init_output'
       inet_sk_flowi_flags(sk), faddr, saddr, 0, 0);
       ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/net_namespace.h:12:0,
                 from /home/timi/android/hwgra_kernel/android_kernel_hwgra/include/linux/netdevice.h:43,
                 from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:33:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/flow.h:88:20: note: declared here
 static inline void flowi4_init_output(struct flowi4 *fl4, int oif,
                    ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c: At top level:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:636:12: error: static declaration of 'ping_recvmsg' follows non-static declaration
 static int ping_recvmsg(struct kiocb *iocb, struct sock *sk, struct msghdr *msg,
            ^
In file included from /home/timi/android/hwgra_kernel/android_kernel_hwgra/net/ipv4/ping.c:43:0:
/home/timi/android/hwgra_kernel/android_kernel_hwgra/include/net/ping.h:78:6: note: previous declaration of 'ping_recvmsg' was here
 int  ping_recvmsg(struct kiocb *iocb, struct sock *sk, struct msghdr *msg,
      ^
/home/timi/android/hwgra_kernel/android_kernel_hwgra/scripts/Makefile.build:316: recipe for target 'net/ipv4/ping.o' failed
make[3]: *** [net/ipv4/ping.o] Error 1
/home/timi/android/hwgra_kernel/android_kernel_hwgra/scripts/Makefile.build:468: recipe for target 'net/ipv4' failed
make[2]: *** [net/ipv4] Error 2
make[2]: *** Waiting for unfinished jobs....
/home/timi/android/hwgra_kernel/android_kernel_hwgra/Makefile:905: recipe for target 'net' failed
make[1]: *** [net] Error 2
make[1]: *** Waiting for unfinished jobs....
/home/timi/android/hwgra_kernel/android_kernel_hwgra/drivers/huawei_platform/connectivity/bcm/wifi/driver/bcmdhd/Makefile:187: CONFIG_BCM4334
/home/timi/android/hwgra_kernel/android_kernel_hwgra/drivers/hisi/modem_hi3xxx/oam/gu/Kbuild:105: CFG_OS_ANDROID_AARCH64_suyi = YES
Makefile:130: recipe for target 'sub-make' failed
make: *** [sub-make] Error 2`

Using the old file temporarily. Maybe you could check if there is some issues?

**Comment by T1mpp4** [comment]
Do you know if this applies to 3.10.x

> These patches are not incremental, meaning that for example the 4.7.3 patch does not apply on top of the 4.7.2 kernel source, but rather on top of the base 4.7 kernel source.

So, in order to apply the 4.7.3 patch to your existing 4.7.2 kernel source you have to first back out the 4.7.2 patch (so you are left with a base 4.7 kernel source) and then apply the new 4.7.3 patch.

https://www.kernel.org/doc/html/v4.11/process/applying-patches.html

**Comment by zeadope** [comment]
@T1mpp4 That would be strange. Since it's called incremental 105-106..

**Comment by zeadope** [comment]
@T1mpp4 

I hard for me to read your copy past there, can you do like a pastbin? But I can already see that:
- This include/net/ping.h contains a lot more (conflicting) lines of code than in Kernel stable 3.10.105/106 include/net/ping.h Replacing ping.h should help.
- include/net/net_namespace.h line 12 contains #include <net/flow.h>, that is not there in stable 105/106.

**Comment by T1mpp4** [comment]
@zeadope 
https://pastebin.ca/4022409 . After the new pull request.

**Comment by zeadope** [comment]
@T1mpp4 Thanks for the pastebin! At least I can see an improvement.

I will try later, it is already late here.

**Comment by zeadope** [comment]
@T1mpp4 
I could not leave it alone, haha. I think I fixed the ping_err issue.

**Comment by T1mpp4** [comment]
Thanks!

**Comment by zeadope** [comment]
@T1mpp4 
I hope it compiles now. I'm glad I can contribute.
Thank you for helping us P8 owners with a new ROM!

**Pull request merged**
